version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: fishlist_db
    environment:
      POSTGRES_DB: fishlist
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - fishlist_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  fishlist_data:
